### ISSUE TITLE
Node stoped updating

### ISSUE THREAD

**Issue by QwertyWhore** [geckogecko/storj_hoststats_app#5] opened 2018-02-24 22:26 UTC
The date on the graph is still stuck in 2017 for both RT and Reputation tabs...
When synced with StorjDash the date comes current for Shared tab.

All other information is current.

**Comment by robally215** [comment] 2018-02-24 22:38
Screenshot

**Comment by robally215** [comment] 2018-02-24 22:39
https://imgur.com/a/R1pME

**Comment by QwertyWhore** [comment] 2018-02-24 22:40
Screenshot , https://imgur.com/a/R1pME

**Comment by geckogecko** [comment] 2018-02-26 10:16
@robally215 Hi thanks for creating an issue. I already noticed this bug in December 2017 and it should be fixed since then. 
Sadly you need to restart your phone **or**  deinstall and install the app- to restart the tracking of your nodes.

Let me know if you still have this issue with the current version and after a restart of your phone.

**Comment by QwertyWhore** [comment] 2018-02-26 20:13
Hey,
 So I've been pretty keen on staying updated. I did have 1.31 installed.
The phone had been restarted over a dozen times since then. So I cleared the cache and that put the time to mid Jan. 
Then decided to just reinstall and that worked. Once installed I imported the nodes via the storjdash api and everything is current. I'll close this out, but keep an eye on it over the next few months.

Thank you again for the app.

**Comment by geckogecko** [comment] 2018-03-14 07:39
Reopened since another user reported the same issue

**Comment by geckogecko** [comment] 2018-05-23 05:20
I have a longtime test running for ~2 months (with the newest version 1.3.2) and was not able to reproduce this issue again -> closing

**Closed as completed by geckogecko** 2018-05-23 05:20 UTC
